#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 30 16:25:52 2021

@author: ihjas
"""

import cv2
face_cascade = cv2.CascasdeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascasdeClassifier("haarcascade_eye.xml")

def detect(gray,frame):
    